site_name: Rail-RNA v0.1
pages:
- Home: index.md
- Installation: installation.md
- Tutorial: tutorial.md
- Deliverables: deliverables.md
- dbGaP_setup: dbgap_setup.md
- Reference: reference.md
theme: flatly
